# Generated by Django 4.2.28 on 2026-02-14 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_userpreferences_allow_sections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspaces", "0005_alter_workspace_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="workspace",
            name="roles",
        ),
        migrations.RemoveField(
            model_name="workspace",
            name="users",
        ),
        migrations.AddField(
            model_name="workspace",
            name="groups_managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="workspaces_groups_managed",
                to="users.group",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="roles_managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="workspaces_roles_managed",
                to="users.role",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="users_managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="workspaces_users_managed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
