# Generated by Django 4.2.28 on 2026-02-14 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0011_userpreferences_allow_sections"),
        (
            "workspaces",
            "0006_remove_workspace_groups_remove_workspace_roles_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="actions_allowed_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="workspaces_actions_allowed_groups",
                to="users.group",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="actions_allowed_roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="workspaces_actions_allowed_roles",
                to="users.role",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="actions_allowed_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="workspaces_actions_allowed_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
