# Generated by Django 4.2.26 on 2026-02-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0005_systeminfo_allow_showing_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="systeminfo",
            name="allow_custom_order",
            field=models.BooleanField(default=False),
        ),
    ]
