# Generated by Django 4.2.26 on 2026-02-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0018_alter_action_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="delayBeforeRelaunch",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Delay (in milliseconds) before relaunching the action.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="hasDelaybeforeRelaunch",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if there is a delay before relaunching the action.",
            ),
        ),
        migrations.AddField(
            model_name="historicalaction",
            name="delayBeforeRelaunch",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Delay (in milliseconds) before relaunching the action.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalaction",
            name="hasDelaybeforeRelaunch",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if there is a delay before relaunching the action.",
            ),
        ),
    ]
