# Generated by Django 4.2.26 on 2026-02-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0019_action_delaybeforerelaunch_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="action",
            old_name="hasDelayBeforeRelaunch",
            new_name="has_delay_before_relaunch",
        ),
        migrations.RenameField(
            model_name="historicalaction",
            old_name="hasDelayBeforeRelaunch",
            new_name="has_delay_before_relaunch",
        ),
        migrations.RemoveField(
            model_name="action",
            name="delayBeforeRelaunch",
        ),
        migrations.RemoveField(
            model_name="historicalaction",
            name="delayBeforeRelaunch",
        ),
        migrations.AddField(
            model_name="action",
            name="delay_before_relaunch",
            field=models.PositiveIntegerField(
                blank=True,
                default=2000,
                help_text="Delay (in milliseconds) before relaunching the action.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalaction",
            name="delay_before_relaunch",
            field=models.PositiveIntegerField(
                blank=True,
                default=2000,
                help_text="Delay (in milliseconds) before relaunching the action.",
                null=True,
            ),
        ),
    ]
