# Generated by Django 4.2.28 on 2026-02-14 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "actions",
            "0020_rename_hasdelaybeforerelaunch_action_has_delay_before_relaunch_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="JavascriptActionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.TextField(
                        default="function run() {\n  console.log('Hello world') }"
                    ),
                ),
                ("use_combobox", models.BooleanField(default=False)),
                (
                    "combobox_code",
                    models.TextField(
                        default="def get_options(context):\r\n    return ['Option 1', 'Option 2']"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalJavascriptActionData",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.TextField(
                        default="function run() {\n  console.log('Hello world') }"
                    ),
                ),
                ("use_combobox", models.BooleanField(default=False)),
                (
                    "combobox_code",
                    models.TextField(
                        default="def get_options(context):\r\n    return ['Option 1', 'Option 2']"
                    ),
                ),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical javascript action data",
                "verbose_name_plural": "historical javascript action datas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
