# Generated by Django 4.2.28 on 2026-02-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0021_javascriptactiondata_historicaljavascriptactiondata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljavascriptactiondata",
            name="code",
            field=models.TextField(
                default="function run() {\n  console.log('Hello world') }\n\nmodule.exports = { run }"
            ),
        ),
        migrations.AlterField(
            model_name="javascriptactiondata",
            name="code",
            field=models.TextField(
                default="function run() {\n  console.log('Hello world') }\n\nmodule.exports = { run }"
            ),
        ),
    ]
