# Generated by Django 4.2.26 on 2026-01-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0018_alter_action_description_and_more"),
        ("users", "0007_userpreferences_allow_showing_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="hidden_actions",
            field=models.ManyToManyField(
                blank=True, related_name="hidden_by_users", to="actions.action"
            ),
        ),
    ]
