# Generated by Django 4.2.26 on 2026-02-01 10:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_userpreferences_hidden_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="custom_order",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
