# Generated by Django 4.2.26 on 2026-02-01 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_userpreferences_allow_custom_order"),
        ("users", "0009_userpreferences_custom_order"),
    ]

    operations = []
