# Generated by Django 4.2.26 on 2026-02-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_merge_20260201_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="allow_sections",
            field=models.BooleanField(default=True),
        ),
    ]
